syntax = "proto3";

package gamelauncher;

service GameService
{
	rpc CheckVersion (VersionRequest) return (VersionResponse);

	rpc DownloadGame (DownloadRequest) return (stream GameData);

	rpc WaitUpdate (Identificial) return (stream UpdateNotice);
}

message VersionRequest
{
	string game_id = 1;
}

message VersionResponse
{
	string latest_version = 1;
	bool is_update_available = 2;
}

message DownloadRequest
{
	string game_id = 1;
	string version = 2;
}

message GameData
{
	bytes data = 1;
	int32 index = 2;
}

message Identificial
{
	string ip_addr = 1;
}

message UpdateNotice
{
	string game_id = 1;
	string version = 2;
}
